server:
  port: 8082

spring:
  application:
    name: lab-entrypoint
  banner:
    charset: UTF-8 # Ou UTF-8, us-ascii, dependendo do conteúdo
    location: banner.txt
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jackson:
    # Não retorna campo nulo no response
    default-property-inclusion: non_null
  autoconfigure:
    exclude:
      # Exclusão de autoconfiguração JPA/Hibernate
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  # Configuração para Cloud AWS (LocalStack)
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ${AWS_REGION}
      sns:
        endpoint: ${AWS_SNS_ENDPOINT}
      sqs:
        endpoint: ${AWS_SQS_ENDPOINT}
        queues:
          partial: ${SQS_QUEUE_PARTIAL}
          total: ${SQS_QUEUE_TOTAL}
          overmeasure: ${SQS_QUEUE_OVERMEASURE}

  logging:
    level:
      root: ${LOGGING_LEVEL:info}
      org:
        springframework:
          data:
            mongodb:
              core:
                MongoTemplate: INFO
              repository:
                query: INFO
